name: Deploy to Subdomain via SFTP

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP
        uses: wlix/sftp-deploy-action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          sftp_only: true
          remote_dir: /public_html/deril/
          exclude: .git/*,.github/*,node_modules/*,vendor/*
