name: Deploy to Subdomain via SFTP

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via SFTP
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: "" # Biarkan kosong jika menggunakan password
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: "22"
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          TARGET: "/public_html/deril/"
          EXCLUDE: "/.git/, /.github/, /node_modules/, /vendor/"
